### PR TITLE
Added problem 485

### PR DESCRIPTION
**Pull request by georgenetu**
Should be fine now. :)

### CODE REVIEW

**Comment by imsky** [comment]
👏

**Comment by georgenetu** [comment]
Thanks. May this be merged then?

**Comment by imsky** [comment]
yes go head

**Comment by georgenetu** [comment]
I think we need someone with writing rights to do that :)

**Comment by imsky** [comment]
ok will merge for you

and will add you to contributors 😄

**Comment by georgenetu** [comment]
Thanks!

**Pull request merged**
