### PR TITLE
Added problem's titles.

### PR DESCRIPTION
**Pull request by yehoshuapw**
added problems titles, as a subheader.(H2)

so now for example problem 33 is:

Problem 33
===========

Digit cancelling fractions
-----------
...

### CODE REVIEW

**Comment by imsky** [comment]
👏

**Comment by yehoshuapw** [comment]
rebased, and redid, with some fixes so won't need to do this each time, and merging should be enough. (most of my addition was adding lines, but I also before hade the `---------` part constant length, so there were conflicts. Now only adds in the subtitle.)

**Comment by yehoshuapw** [comment]
I connected all the pieces of scripts I used, and added in the 'by hand' changes and edited into a single script, that does my job. [script](http://homedir.jct.ac.il/~ywallach/script). It's not very elegant, since I didn't program it as a script, but glued together scriptlets i made, and changed a bit here and there to be easy to change some things.

Anyways, should I add that in?

**Comment by imsky** [comment]
feel free to add it in

**Comment by jayvdb** [comment]
Could you replace `/home/ypw/` with `~`, and use `mkdir -p` to make the base directories if they are missing.
Note there are Python libraries that can be used to fetch PE problem data (titles and problem text), but if this script works for you, and it also works when someone else runs it, then 👍 from me too.

**Comment by yehoshuapw** [comment]
Those 2 lines are supposed to be edited, since `defaultpath` should be where README.md is, and `defaultthingspath` where the script and it's files should be. I can leave them empty, and ask for them, or create directories. 

Should i leave empty, and if it's empty ask, or just tell the user to edit them? or should  create directories? (If i do directories, a more generalized locations is probably better. any suggestions?)

**Comment by jayvdb** [comment]
Well README.md and the script will be in the repo, so they will share the same base directory, which you can derive from ` $0`.
The files directory can be also in the same base path, with that subdirectory added to `.gitignore` so it isnt committed.

**Comment by yehoshuapw** [comment]
should I squash this?

**Comment by imsky** [comment]
yes please squash this

**Comment by yehoshuapw** [comment]
rebased again (onto), instead of just merging, since also added a newline to the end of the file, making the diff both ways, and so conflicting.

**Comment by georgenetu** [comment]
Can / Should we merge this? @imsky @jayvdb

**Comment by imsky** [comment]
let's do it @georgenetu

**Pull request merged**
