### PR TITLE
Added Problem 483

### PR DESCRIPTION
**Pull request by georgenetu**

### CODE REVIEW

**Comment by yehoshuapw** [comment]
This, and a 471, 481 use this notation, which is correct markdown, but isn't the same as the rest, which use [] for subscript, and ^ for superscript. I am not sure which one should be used, but think it would be better if they are all the same.

**Comment by imsky** [comment]
please us brackets for subscript, etc.

**Comment by georgenetu** [comment]
Will do another Pull Request for 471, 473 etc.

**Comment by yehoshuapw** [comment]
not any more.

**Comment by yehoshuapw** [comment]
not anymore. see See #62

**Comment by imsky** [comment]
@georgenetu ready for review?

**Comment by georgenetu** [comment]
Yes, of course.

**Comment by imsky** [comment]
👍

**Comment by georgenetu** [comment]
Hi @imsky, @yehoshuapw. I need some advice regarding the usage of subscript. Problem 486 has something like F<sub>5</sub>(n), but I can't use it, so this will need to be converted to F[5](n) which is a hyperlink. How should I approach this issue?

**Comment by yehoshuapw** [comment]
have a look at Problem 137. seems to be done there, and works. I think the trick is having quotes around it.
(`A[F](x)` = xF[1] + ...)

**Comment by georgenetu** [comment]
Great tip, thanks

**Pull request merged**
