### PR TITLE
added titles.

### PR DESCRIPTION
**Pull request by yehoshuapw**
added the titles PE gives the problems.
(for example problem 328:  old:"Problem 328" new:"Problem 328: Lowest-cost Search")

### CODE REVIEW

**Comment by imsky** [comment]
:+1:

**Comment by jayvdb** [comment]
Four markdown errors according to Travis lint tools

- README.md:3539: MD026 Trailing punctuation in header
- README.md:4314: MD026 Trailing punctuation in header
- README.md:6095: MD026 Trailing punctuation in header
- README.md:9610: MD026 Trailing punctuation in header

**Comment by yehoshuapw** [comment]
those are titles that finish with "?" and "!".
(Problem 145: How many reversible numbers are there below one-billion?
Problem 173: Using up to one million tiles how many different "hollow" square laminae can be formed?
Problem 248: Numbers for which Euler’s totient function equals 13!
Problem 380: Amazing Mazes!)
it is not a problem to remove them, but should I, or just ignore the lint?

**Comment by jayvdb** [comment]
See #62

**Comment by jayvdb** [comment]
@yehoshuapw , can you squash your commits into a single commit?

**Comment by yehoshuapw** [comment]
should i squash also these two? or lrave it like this?

**Comment by jayvdb** [comment]
Looking _much_ better.
However, not quite there.

Could you rebase your commit onto the latest master commit cb49f00 ?

**Comment by yehoshuapw** [comment]
you mean remove the "Use released version of remark" commit at here?

**Comment by yehoshuapw** [comment]
git cloed this, and reopend a new one. #64

**Pull request closed without merging**
